language: ruby

rvm:
  - 2.7.2

gemfile: "Gemfile"

before_install:
  - sudo apt-get install libsodium-dev -y

sudo: false

env:
  global:
    - VERBOSE=true
    - TIMEOUT=1

branches:
  only:
    - master

services:
  - redis-server
